server:
  port: 8080
spring:
  application:
    name: model-gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.177.128  # 修改后的Nacos 服务器地址
        port: 8848

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 30000
        loggerLevel: full
  okhttp:
    enabled: true # 开启OKHttp功能
  httpclient:
    enabled: true

