server:
  port: 8080

spring:
  application:
    name: his-service
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://${hm.db.host}:3306/his?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${hm.db.pw}
  redis:
    host: 111.230.32.147
    port: 9631
    password: 4+K/D2zvxHooBhn5begcMQz/04IpAMpq
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
    database: 0
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
  main:
    allow-bean-definition-overriding: true

mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto
  mapper-locations: classpath*:/mapper/**/*.xml
logging:
  level:
    com.luojiawei: debug
  pattern:
    dateformat: HH:mm:ss:SSS
  file:
    path: "logs/${spring.application.name}"
knife4j:
  enable: true
  openapi:
    title: 智能眼疾诊断接口文档
    description: "智能眼疾诊断系统文档"
    email: 2240774934@qq.com
    concat: 罗佳炜
    version: v1.0.0
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - com.luojiawei.service.controller
