server:
  port: 8080

spring:
  application:
    name: his-service
  cloud:
    nacos:
      discovery:
        server-addr: 81.71.3.20
        port: 8848
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://111.230.32.147:3306/ai_eyes_diagnosis
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${hm.db.pw}
  redis:
    host: 111.230.32.147
    port: 9631
    password: 4+K/D2zvxHooBhn5begcMQz/04IpAMpq
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
    database: 0
  jackson:
    default-property-inclusion: non_null
  main:
    allow-bean-definition-overriding: true

mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto
  mapper-locations: classpath*:/mapper/**/*.xml
logging:
  level:
    org.springframework.cloud.openfeign: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
    org.springframework.cloud.client.loadbalancer: DEBUG
    com.luojiawei: debug
  pattern:
    dateformat: HH:mm:ss:SSS
  file:
    path: "logs/${spring.application.name}"

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 30000
        loggerLevel: full
      ai-doctor-service:
        connectTimeout: 60000
        readTimeout: 60000
  okhttp:
    enabled: true

knife4j:
  enable: true
  openapi:
    title: 智能眼疾诊断接口文档
    description: "智能眼疾诊断系统文档"
    email: 2240774934@qq.com
    concat: 罗佳炜
    version: v1.0.0
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - com.luojiawei.service.controller